// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP915I-Klx8ZvsNYObCf2vr1fYWzuiK4c',
    appId: '1:158812712668:web:1be3bf0f369972449a4e19',
    messagingSenderId: '158812712668',
    projectId: 'women-safety-ff1b9',
    authDomain: 'women-safety-ff1b9.firebaseapp.com',
    storageBucket: 'women-safety-ff1b9.firebasestorage.app',
    measurementId: 'G-DYTQCNT2SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy8Fe0upPf_O6B6bnRYfTNw2QgVmgfOwk',
    appId: '1:158812712668:android:63f3eedb831b975b9a4e19',
    messagingSenderId: '158812712668',
    projectId: 'women-safety-ff1b9',
    storageBucket: 'women-safety-ff1b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkQmHuqdyZntObrWWuSpZZlTRJeI2hIyI',
    appId: '1:158812712668:ios:b084e3896a92672a9a4e19',
    messagingSenderId: '158812712668',
    projectId: 'women-safety-ff1b9',
    storageBucket: 'women-safety-ff1b9.firebasestorage.app',
    iosBundleId: 'com.example.womenSaftey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkQmHuqdyZntObrWWuSpZZlTRJeI2hIyI',
    appId: '1:158812712668:ios:b084e3896a92672a9a4e19',
    messagingSenderId: '158812712668',
    projectId: 'women-safety-ff1b9',
    storageBucket: 'women-safety-ff1b9.firebasestorage.app',
    iosBundleId: 'com.example.womenSaftey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP915I-Klx8ZvsNYObCf2vr1fYWzuiK4c',
    appId: '1:158812712668:web:fac71c5f8ba92f769a4e19',
    messagingSenderId: '158812712668',
    projectId: 'women-safety-ff1b9',
    authDomain: 'women-safety-ff1b9.firebaseapp.com',
    storageBucket: 'women-safety-ff1b9.firebasestorage.app',
    measurementId: 'G-9DC85DFW9F',
  );
}
